version: "3.9"

services:
  ratmm:
    build:
      context: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t      
    env_file:
      - .env
    volumes:
      - .:/app






